# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _mbisdk
else:
    import _mbisdk

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _mbisdk.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mbisdk.delete_SwigPyIterator

    def value(self):
        return _mbisdk.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _mbisdk.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _mbisdk.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _mbisdk.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _mbisdk.SwigPyIterator_equal(self, x)

    def copy(self):
        return _mbisdk.SwigPyIterator_copy(self)

    def next(self):
        return _mbisdk.SwigPyIterator_next(self)

    def __next__(self):
        return _mbisdk.SwigPyIterator___next__(self)

    def previous(self):
        return _mbisdk.SwigPyIterator_previous(self)

    def advance(self, n):
        return _mbisdk.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _mbisdk.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _mbisdk.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _mbisdk.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _mbisdk.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _mbisdk.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _mbisdk.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _mbisdk:
_mbisdk.SwigPyIterator_swigregister(SwigPyIterator)
class PairDblInt64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.PairDblInt64_swiginit(self, _mbisdk.new_PairDblInt64(*args))
    first = property(_mbisdk.PairDblInt64_first_get, _mbisdk.PairDblInt64_first_set)
    second = property(_mbisdk.PairDblInt64_second_get, _mbisdk.PairDblInt64_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _mbisdk.delete_PairDblInt64

# Register PairDblInt64 in _mbisdk:
_mbisdk.PairDblInt64_swigregister(PairDblInt64)
class PtrFrame(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mbisdk.PtrFrame_swiginit(self, _mbisdk.new_PtrFrame())
    __swig_destroy__ = _mbisdk.delete_PtrFrame

# Register PtrFrame in _mbisdk:
_mbisdk.PtrFrame_swigregister(PtrFrame)
class PtrFrameMetaData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mbisdk.PtrFrameMetaData_swiginit(self, _mbisdk.new_PtrFrameMetaData())
    __swig_destroy__ = _mbisdk.delete_PtrFrameMetaData

# Register PtrFrameMetaData in _mbisdk:
_mbisdk.PtrFrameMetaData_swigregister(PtrFrameMetaData)
class MapStringString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.MapStringString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.MapStringString___nonzero__(self)

    def __bool__(self):
        return _mbisdk.MapStringString___bool__(self)

    def __len__(self):
        return _mbisdk.MapStringString___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _mbisdk.MapStringString___getitem__(self, key)

    def __delitem__(self, key):
        return _mbisdk.MapStringString___delitem__(self, key)

    def has_key(self, key):
        return _mbisdk.MapStringString_has_key(self, key)

    def keys(self):
        return _mbisdk.MapStringString_keys(self)

    def values(self):
        return _mbisdk.MapStringString_values(self)

    def items(self):
        return _mbisdk.MapStringString_items(self)

    def __contains__(self, key):
        return _mbisdk.MapStringString___contains__(self, key)

    def key_iterator(self):
        return _mbisdk.MapStringString_key_iterator(self)

    def value_iterator(self):
        return _mbisdk.MapStringString_value_iterator(self)

    def __setitem__(self, *args):
        return _mbisdk.MapStringString___setitem__(self, *args)

    def asdict(self):
        return _mbisdk.MapStringString_asdict(self)

    def __init__(self, *args):
        _mbisdk.MapStringString_swiginit(self, _mbisdk.new_MapStringString(*args))

    def empty(self):
        return _mbisdk.MapStringString_empty(self)

    def size(self):
        return _mbisdk.MapStringString_size(self)

    def swap(self, v):
        return _mbisdk.MapStringString_swap(self, v)

    def begin(self):
        return _mbisdk.MapStringString_begin(self)

    def end(self):
        return _mbisdk.MapStringString_end(self)

    def rbegin(self):
        return _mbisdk.MapStringString_rbegin(self)

    def rend(self):
        return _mbisdk.MapStringString_rend(self)

    def clear(self):
        return _mbisdk.MapStringString_clear(self)

    def get_allocator(self):
        return _mbisdk.MapStringString_get_allocator(self)

    def count(self, x):
        return _mbisdk.MapStringString_count(self, x)

    def erase(self, *args):
        return _mbisdk.MapStringString_erase(self, *args)

    def find(self, x):
        return _mbisdk.MapStringString_find(self, x)

    def lower_bound(self, x):
        return _mbisdk.MapStringString_lower_bound(self, x)

    def upper_bound(self, x):
        return _mbisdk.MapStringString_upper_bound(self, x)
    __swig_destroy__ = _mbisdk.delete_MapStringString

# Register MapStringString in _mbisdk:
_mbisdk.MapStringString_swigregister(MapStringString)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _mbisdk.DoubleVector___bool__(self)

    def __len__(self):
        return _mbisdk.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _mbisdk.DoubleVector_pop(self)

    def append(self, x):
        return _mbisdk.DoubleVector_append(self, x)

    def empty(self):
        return _mbisdk.DoubleVector_empty(self)

    def size(self):
        return _mbisdk.DoubleVector_size(self)

    def swap(self, v):
        return _mbisdk.DoubleVector_swap(self, v)

    def begin(self):
        return _mbisdk.DoubleVector_begin(self)

    def end(self):
        return _mbisdk.DoubleVector_end(self)

    def rbegin(self):
        return _mbisdk.DoubleVector_rbegin(self)

    def rend(self):
        return _mbisdk.DoubleVector_rend(self)

    def clear(self):
        return _mbisdk.DoubleVector_clear(self)

    def get_allocator(self):
        return _mbisdk.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _mbisdk.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _mbisdk.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.DoubleVector_swiginit(self, _mbisdk.new_DoubleVector(*args))

    def push_back(self, x):
        return _mbisdk.DoubleVector_push_back(self, x)

    def front(self):
        return _mbisdk.DoubleVector_front(self)

    def back(self):
        return _mbisdk.DoubleVector_back(self)

    def assign(self, n, x):
        return _mbisdk.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.DoubleVector_reserve(self, n)

    def capacity(self):
        return _mbisdk.DoubleVector_capacity(self)
    __swig_destroy__ = _mbisdk.delete_DoubleVector

# Register DoubleVector in _mbisdk:
_mbisdk.DoubleVector_swigregister(DoubleVector)
class FloatVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.FloatVector___nonzero__(self)

    def __bool__(self):
        return _mbisdk.FloatVector___bool__(self)

    def __len__(self):
        return _mbisdk.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.FloatVector___setitem__(self, *args)

    def pop(self):
        return _mbisdk.FloatVector_pop(self)

    def append(self, x):
        return _mbisdk.FloatVector_append(self, x)

    def empty(self):
        return _mbisdk.FloatVector_empty(self)

    def size(self):
        return _mbisdk.FloatVector_size(self)

    def swap(self, v):
        return _mbisdk.FloatVector_swap(self, v)

    def begin(self):
        return _mbisdk.FloatVector_begin(self)

    def end(self):
        return _mbisdk.FloatVector_end(self)

    def rbegin(self):
        return _mbisdk.FloatVector_rbegin(self)

    def rend(self):
        return _mbisdk.FloatVector_rend(self)

    def clear(self):
        return _mbisdk.FloatVector_clear(self)

    def get_allocator(self):
        return _mbisdk.FloatVector_get_allocator(self)

    def pop_back(self):
        return _mbisdk.FloatVector_pop_back(self)

    def erase(self, *args):
        return _mbisdk.FloatVector_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.FloatVector_swiginit(self, _mbisdk.new_FloatVector(*args))

    def push_back(self, x):
        return _mbisdk.FloatVector_push_back(self, x)

    def front(self):
        return _mbisdk.FloatVector_front(self)

    def back(self):
        return _mbisdk.FloatVector_back(self)

    def assign(self, n, x):
        return _mbisdk.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.FloatVector_reserve(self, n)

    def capacity(self):
        return _mbisdk.FloatVector_capacity(self)
    __swig_destroy__ = _mbisdk.delete_FloatVector

# Register FloatVector in _mbisdk:
_mbisdk.FloatVector_swigregister(FloatVector)
class Int32Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.Int32Vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.Int32Vector___nonzero__(self)

    def __bool__(self):
        return _mbisdk.Int32Vector___bool__(self)

    def __len__(self):
        return _mbisdk.Int32Vector___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.Int32Vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.Int32Vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.Int32Vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.Int32Vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.Int32Vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.Int32Vector___setitem__(self, *args)

    def pop(self):
        return _mbisdk.Int32Vector_pop(self)

    def append(self, x):
        return _mbisdk.Int32Vector_append(self, x)

    def empty(self):
        return _mbisdk.Int32Vector_empty(self)

    def size(self):
        return _mbisdk.Int32Vector_size(self)

    def swap(self, v):
        return _mbisdk.Int32Vector_swap(self, v)

    def begin(self):
        return _mbisdk.Int32Vector_begin(self)

    def end(self):
        return _mbisdk.Int32Vector_end(self)

    def rbegin(self):
        return _mbisdk.Int32Vector_rbegin(self)

    def rend(self):
        return _mbisdk.Int32Vector_rend(self)

    def clear(self):
        return _mbisdk.Int32Vector_clear(self)

    def get_allocator(self):
        return _mbisdk.Int32Vector_get_allocator(self)

    def pop_back(self):
        return _mbisdk.Int32Vector_pop_back(self)

    def erase(self, *args):
        return _mbisdk.Int32Vector_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.Int32Vector_swiginit(self, _mbisdk.new_Int32Vector(*args))

    def push_back(self, x):
        return _mbisdk.Int32Vector_push_back(self, x)

    def front(self):
        return _mbisdk.Int32Vector_front(self)

    def back(self):
        return _mbisdk.Int32Vector_back(self)

    def assign(self, n, x):
        return _mbisdk.Int32Vector_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.Int32Vector_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.Int32Vector_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.Int32Vector_reserve(self, n)

    def capacity(self):
        return _mbisdk.Int32Vector_capacity(self)
    __swig_destroy__ = _mbisdk.delete_Int32Vector

# Register Int32Vector in _mbisdk:
_mbisdk.Int32Vector_swigregister(Int32Vector)
class Int64Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.Int64Vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.Int64Vector___nonzero__(self)

    def __bool__(self):
        return _mbisdk.Int64Vector___bool__(self)

    def __len__(self):
        return _mbisdk.Int64Vector___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.Int64Vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.Int64Vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.Int64Vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.Int64Vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.Int64Vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.Int64Vector___setitem__(self, *args)

    def pop(self):
        return _mbisdk.Int64Vector_pop(self)

    def append(self, x):
        return _mbisdk.Int64Vector_append(self, x)

    def empty(self):
        return _mbisdk.Int64Vector_empty(self)

    def size(self):
        return _mbisdk.Int64Vector_size(self)

    def swap(self, v):
        return _mbisdk.Int64Vector_swap(self, v)

    def begin(self):
        return _mbisdk.Int64Vector_begin(self)

    def end(self):
        return _mbisdk.Int64Vector_end(self)

    def rbegin(self):
        return _mbisdk.Int64Vector_rbegin(self)

    def rend(self):
        return _mbisdk.Int64Vector_rend(self)

    def clear(self):
        return _mbisdk.Int64Vector_clear(self)

    def get_allocator(self):
        return _mbisdk.Int64Vector_get_allocator(self)

    def pop_back(self):
        return _mbisdk.Int64Vector_pop_back(self)

    def erase(self, *args):
        return _mbisdk.Int64Vector_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.Int64Vector_swiginit(self, _mbisdk.new_Int64Vector(*args))

    def push_back(self, x):
        return _mbisdk.Int64Vector_push_back(self, x)

    def front(self):
        return _mbisdk.Int64Vector_front(self)

    def back(self):
        return _mbisdk.Int64Vector_back(self)

    def assign(self, n, x):
        return _mbisdk.Int64Vector_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.Int64Vector_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.Int64Vector_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.Int64Vector_reserve(self, n)

    def capacity(self):
        return _mbisdk.Int64Vector_capacity(self)
    __swig_destroy__ = _mbisdk.delete_Int64Vector

# Register Int64Vector in _mbisdk:
_mbisdk.Int64Vector_swigregister(Int64Vector)
class SizeTVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.SizeTVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.SizeTVector___nonzero__(self)

    def __bool__(self):
        return _mbisdk.SizeTVector___bool__(self)

    def __len__(self):
        return _mbisdk.SizeTVector___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.SizeTVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.SizeTVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.SizeTVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.SizeTVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.SizeTVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.SizeTVector___setitem__(self, *args)

    def pop(self):
        return _mbisdk.SizeTVector_pop(self)

    def append(self, x):
        return _mbisdk.SizeTVector_append(self, x)

    def empty(self):
        return _mbisdk.SizeTVector_empty(self)

    def size(self):
        return _mbisdk.SizeTVector_size(self)

    def swap(self, v):
        return _mbisdk.SizeTVector_swap(self, v)

    def begin(self):
        return _mbisdk.SizeTVector_begin(self)

    def end(self):
        return _mbisdk.SizeTVector_end(self)

    def rbegin(self):
        return _mbisdk.SizeTVector_rbegin(self)

    def rend(self):
        return _mbisdk.SizeTVector_rend(self)

    def clear(self):
        return _mbisdk.SizeTVector_clear(self)

    def get_allocator(self):
        return _mbisdk.SizeTVector_get_allocator(self)

    def pop_back(self):
        return _mbisdk.SizeTVector_pop_back(self)

    def erase(self, *args):
        return _mbisdk.SizeTVector_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.SizeTVector_swiginit(self, _mbisdk.new_SizeTVector(*args))

    def push_back(self, x):
        return _mbisdk.SizeTVector_push_back(self, x)

    def front(self):
        return _mbisdk.SizeTVector_front(self)

    def back(self):
        return _mbisdk.SizeTVector_back(self)

    def assign(self, n, x):
        return _mbisdk.SizeTVector_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.SizeTVector_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.SizeTVector_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.SizeTVector_reserve(self, n)

    def capacity(self):
        return _mbisdk.SizeTVector_capacity(self)
    __swig_destroy__ = _mbisdk.delete_SizeTVector

# Register SizeTVector in _mbisdk:
_mbisdk.SizeTVector_swigregister(SizeTVector)
class VectorPairIntInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.VectorPairIntInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.VectorPairIntInt___nonzero__(self)

    def __bool__(self):
        return _mbisdk.VectorPairIntInt___bool__(self)

    def __len__(self):
        return _mbisdk.VectorPairIntInt___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.VectorPairIntInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.VectorPairIntInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.VectorPairIntInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.VectorPairIntInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.VectorPairIntInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.VectorPairIntInt___setitem__(self, *args)

    def pop(self):
        return _mbisdk.VectorPairIntInt_pop(self)

    def append(self, x):
        return _mbisdk.VectorPairIntInt_append(self, x)

    def empty(self):
        return _mbisdk.VectorPairIntInt_empty(self)

    def size(self):
        return _mbisdk.VectorPairIntInt_size(self)

    def swap(self, v):
        return _mbisdk.VectorPairIntInt_swap(self, v)

    def begin(self):
        return _mbisdk.VectorPairIntInt_begin(self)

    def end(self):
        return _mbisdk.VectorPairIntInt_end(self)

    def rbegin(self):
        return _mbisdk.VectorPairIntInt_rbegin(self)

    def rend(self):
        return _mbisdk.VectorPairIntInt_rend(self)

    def clear(self):
        return _mbisdk.VectorPairIntInt_clear(self)

    def get_allocator(self):
        return _mbisdk.VectorPairIntInt_get_allocator(self)

    def pop_back(self):
        return _mbisdk.VectorPairIntInt_pop_back(self)

    def erase(self, *args):
        return _mbisdk.VectorPairIntInt_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.VectorPairIntInt_swiginit(self, _mbisdk.new_VectorPairIntInt(*args))

    def push_back(self, x):
        return _mbisdk.VectorPairIntInt_push_back(self, x)

    def front(self):
        return _mbisdk.VectorPairIntInt_front(self)

    def back(self):
        return _mbisdk.VectorPairIntInt_back(self)

    def assign(self, n, x):
        return _mbisdk.VectorPairIntInt_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.VectorPairIntInt_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.VectorPairIntInt_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.VectorPairIntInt_reserve(self, n)

    def capacity(self):
        return _mbisdk.VectorPairIntInt_capacity(self)
    __swig_destroy__ = _mbisdk.delete_VectorPairIntInt

# Register VectorPairIntInt in _mbisdk:
_mbisdk.VectorPairIntInt_swigregister(VectorPairIntInt)
class VectorPairInt64Int64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.VectorPairInt64Int64_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.VectorPairInt64Int64___nonzero__(self)

    def __bool__(self):
        return _mbisdk.VectorPairInt64Int64___bool__(self)

    def __len__(self):
        return _mbisdk.VectorPairInt64Int64___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.VectorPairInt64Int64___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.VectorPairInt64Int64___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.VectorPairInt64Int64___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.VectorPairInt64Int64___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.VectorPairInt64Int64___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.VectorPairInt64Int64___setitem__(self, *args)

    def pop(self):
        return _mbisdk.VectorPairInt64Int64_pop(self)

    def append(self, x):
        return _mbisdk.VectorPairInt64Int64_append(self, x)

    def empty(self):
        return _mbisdk.VectorPairInt64Int64_empty(self)

    def size(self):
        return _mbisdk.VectorPairInt64Int64_size(self)

    def swap(self, v):
        return _mbisdk.VectorPairInt64Int64_swap(self, v)

    def begin(self):
        return _mbisdk.VectorPairInt64Int64_begin(self)

    def end(self):
        return _mbisdk.VectorPairInt64Int64_end(self)

    def rbegin(self):
        return _mbisdk.VectorPairInt64Int64_rbegin(self)

    def rend(self):
        return _mbisdk.VectorPairInt64Int64_rend(self)

    def clear(self):
        return _mbisdk.VectorPairInt64Int64_clear(self)

    def get_allocator(self):
        return _mbisdk.VectorPairInt64Int64_get_allocator(self)

    def pop_back(self):
        return _mbisdk.VectorPairInt64Int64_pop_back(self)

    def erase(self, *args):
        return _mbisdk.VectorPairInt64Int64_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.VectorPairInt64Int64_swiginit(self, _mbisdk.new_VectorPairInt64Int64(*args))

    def push_back(self, x):
        return _mbisdk.VectorPairInt64Int64_push_back(self, x)

    def front(self):
        return _mbisdk.VectorPairInt64Int64_front(self)

    def back(self):
        return _mbisdk.VectorPairInt64Int64_back(self)

    def assign(self, n, x):
        return _mbisdk.VectorPairInt64Int64_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.VectorPairInt64Int64_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.VectorPairInt64Int64_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.VectorPairInt64Int64_reserve(self, n)

    def capacity(self):
        return _mbisdk.VectorPairInt64Int64_capacity(self)
    __swig_destroy__ = _mbisdk.delete_VectorPairInt64Int64

# Register VectorPairInt64Int64 in _mbisdk:
_mbisdk.VectorPairInt64Int64_swigregister(VectorPairInt64Int64)
class VectorPairDblInt64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mbisdk.VectorPairDblInt64_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mbisdk.VectorPairDblInt64___nonzero__(self)

    def __bool__(self):
        return _mbisdk.VectorPairDblInt64___bool__(self)

    def __len__(self):
        return _mbisdk.VectorPairDblInt64___len__(self)

    def __getslice__(self, i, j):
        return _mbisdk.VectorPairDblInt64___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mbisdk.VectorPairDblInt64___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mbisdk.VectorPairDblInt64___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mbisdk.VectorPairDblInt64___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mbisdk.VectorPairDblInt64___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mbisdk.VectorPairDblInt64___setitem__(self, *args)

    def pop(self):
        return _mbisdk.VectorPairDblInt64_pop(self)

    def append(self, x):
        return _mbisdk.VectorPairDblInt64_append(self, x)

    def empty(self):
        return _mbisdk.VectorPairDblInt64_empty(self)

    def size(self):
        return _mbisdk.VectorPairDblInt64_size(self)

    def swap(self, v):
        return _mbisdk.VectorPairDblInt64_swap(self, v)

    def begin(self):
        return _mbisdk.VectorPairDblInt64_begin(self)

    def end(self):
        return _mbisdk.VectorPairDblInt64_end(self)

    def rbegin(self):
        return _mbisdk.VectorPairDblInt64_rbegin(self)

    def rend(self):
        return _mbisdk.VectorPairDblInt64_rend(self)

    def clear(self):
        return _mbisdk.VectorPairDblInt64_clear(self)

    def get_allocator(self):
        return _mbisdk.VectorPairDblInt64_get_allocator(self)

    def pop_back(self):
        return _mbisdk.VectorPairDblInt64_pop_back(self)

    def erase(self, *args):
        return _mbisdk.VectorPairDblInt64_erase(self, *args)

    def __init__(self, *args):
        _mbisdk.VectorPairDblInt64_swiginit(self, _mbisdk.new_VectorPairDblInt64(*args))

    def push_back(self, x):
        return _mbisdk.VectorPairDblInt64_push_back(self, x)

    def front(self):
        return _mbisdk.VectorPairDblInt64_front(self)

    def back(self):
        return _mbisdk.VectorPairDblInt64_back(self)

    def assign(self, n, x):
        return _mbisdk.VectorPairDblInt64_assign(self, n, x)

    def resize(self, *args):
        return _mbisdk.VectorPairDblInt64_resize(self, *args)

    def insert(self, *args):
        return _mbisdk.VectorPairDblInt64_insert(self, *args)

    def reserve(self, n):
        return _mbisdk.VectorPairDblInt64_reserve(self, n)

    def capacity(self):
        return _mbisdk.VectorPairDblInt64_capacity(self)
    __swig_destroy__ = _mbisdk.delete_VectorPairDblInt64

# Register VectorPairDblInt64 in _mbisdk:
_mbisdk.VectorPairDblInt64_swigregister(VectorPairDblInt64)
class PairIntInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.PairIntInt_swiginit(self, _mbisdk.new_PairIntInt(*args))
    first = property(_mbisdk.PairIntInt_first_get, _mbisdk.PairIntInt_first_set)
    second = property(_mbisdk.PairIntInt_second_get, _mbisdk.PairIntInt_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _mbisdk.delete_PairIntInt

# Register PairIntInt in _mbisdk:
_mbisdk.PairIntInt_swigregister(PairIntInt)
class PairInt64Int64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.PairInt64Int64_swiginit(self, _mbisdk.new_PairInt64Int64(*args))
    first = property(_mbisdk.PairInt64Int64_first_get, _mbisdk.PairInt64Int64_first_set)
    second = property(_mbisdk.PairInt64Int64_second_get, _mbisdk.PairInt64Int64_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _mbisdk.delete_PairInt64Int64

# Register PairInt64Int64 in _mbisdk:
_mbisdk.PairInt64Int64_swigregister(PairInt64Int64)

def Int64Vector_get(v, index):
    return _mbisdk.Int64Vector_get(v, index)

def Int32Vector_get(v, index):
    return _mbisdk.Int32Vector_get(v, index)

def PairDoubleInt64_get_first(v, index):
    return _mbisdk.PairDoubleInt64_get_first(v, index)

def PairDoubleInt64_get_second(v, index):
    return _mbisdk.PairDoubleInt64_get_second(v, index)
IonPolarity_POSITIVE = _mbisdk.IonPolarity_POSITIVE
IonPolarity_NEGATIVE = _mbisdk.IonPolarity_NEGATIVE
IonPolarity_BOTH = _mbisdk.IonPolarity_BOTH
IonPolarity_UNKNOWN = _mbisdk.IonPolarity_UNKNOWN
class Metadata(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.Metadata_swiginit(self, _mbisdk.new_Metadata(*args))

    def Copy(self, toCopy):
        return _mbisdk.Metadata_Copy(self, toCopy)

    def HasKey(self, key):
        return _mbisdk.Metadata_HasKey(self, key)

    def ReadString(self, *args):
        return _mbisdk.Metadata_ReadString(self, *args)

    def ReadInt(self, key):
        return _mbisdk.Metadata_ReadInt(self, key)

    def ReadDouble(self, key):
        return _mbisdk.Metadata_ReadDouble(self, key)

    def ReadAll(self):
        return _mbisdk.Metadata_ReadAll(self)

    def GetCache(self):
        return _mbisdk.Metadata_GetCache(self)

    def SetCache(self, toCopy):
        return _mbisdk.Metadata_SetCache(self, toCopy)

    def Close(self):
        return _mbisdk.Metadata_Close(self)
    __swig_destroy__ = _mbisdk.delete_Metadata

# Register Metadata in _mbisdk:
_mbisdk.Metadata_swigregister(Metadata)
cvar = _mbisdk.cvar
DATA_DESCRIPTION = cvar.DATA_DESCRIPTION
GLOBAL_DESCRIPTION = cvar.GLOBAL_DESCRIPTION
DATA_CUBES = cvar.DATA_CUBES
SCAN_DEFINITIONS = cvar.SCAN_DEFINITIONS
FRAME_DATA = cvar.FRAME_DATA
FRAME_METADATA = cvar.FRAME_METADATA
INDEX_COUNTS = cvar.INDEX_COUNTS
INDEX_POSITIONS = cvar.INDEX_POSITIONS
DATA_COUNTS = cvar.DATA_COUNTS
DATA_POSITIONS = cvar.DATA_POSITIONS
TRIGGER_TIMESTAMPS = cvar.TRIGGER_TIMESTAMPS
RT_TIC = cvar.RT_TIC
AT_TIC = cvar.AT_TIC
CAL_CCS_TRADITIONAL = cvar.CAL_CCS_TRADITIONAL
SCAN_DEFINITION_TABLE = cvar.SCAN_DEFINITION_TABLE
SCANDEF_SETPOINT_INDICES = cvar.SCANDEF_SETPOINT_INDICES
SCANDEF_INTERPOLATION_MODE = cvar.SCANDEF_INTERPOLATION_MODE
SCANDEF_SETPOINTS = cvar.SCANDEF_SETPOINTS
WINDOW_START = cvar.WINDOW_START
WINDOW_END = cvar.WINDOW_END
ISOLATION_WINDOWS = cvar.ISOLATION_WINDOWS
COLLISION_ENERGY = cvar.COLLISION_ENERGY
SCANDEF_MAPPING = cvar.SCANDEF_MAPPING
CAL_DT_POLYNOMIAL = cvar.CAL_DT_POLYNOMIAL
CAL_DT_POWER_FLAGS = cvar.CAL_DT_POWER_FLAGS
CAL_DT_TRADITIONAL = cvar.CAL_DT_TRADITIONAL
CAL_MS_POLYNOMIAL = cvar.CAL_MS_POLYNOMIAL
CAL_MS_POWER_FLAGS = cvar.CAL_MS_POWER_FLAGS
CAL_MS_TRADITIONAL = cvar.CAL_MS_TRADITIONAL
FRM_COLLISION_ENERGY = cvar.FRM_COLLISION_ENERGY
FRM_DT_PERIOD = cvar.FRM_DT_PERIOD
FRM_FRAG_ENERGY = cvar.FRM_FRAG_ENERGY
FRM_FRAG_ENERGY_MODE = cvar.FRM_FRAG_ENERGY_MODE
FRM_FRAG_OP_MODE = cvar.FRM_FRAG_OP_MODE
FRM_INTENSITY_LIMIT = cvar.FRM_INTENSITY_LIMIT
FRM_METADATA_ID = cvar.FRM_METADATA_ID
FRM_METHOD_NAME = cvar.FRM_METHOD_NAME
FRM_METHOD_STATE = cvar.FRM_METHOD_STATE
FRM_MUX_GATE = cvar.FRM_MUX_GATE
FRM_MUX_SEQUENCE = cvar.FRM_MUX_SEQUENCE
FRM_NUM_SCANS = cvar.FRM_NUM_SCANS
FRM_NUM_MICROFRAMES = cvar.FRM_NUM_MICROFRAMES
FRM_POLARITY = cvar.FRM_POLARITY
FRM_START_TIME = cvar.FRM_START_TIME
FRM_TIMIING_INTENTS = cvar.FRM_TIMIING_INTENTS
KEY_FRAG = cvar.KEY_FRAG
SLIM_RF_FUNNEL_POWER = cvar.SLIM_RF_FUNNEL_POWER
SLM_ENTRANCE_OFFSET = cvar.SLM_ENTRANCE_OFFSET
SLM_EXIT_CL = cvar.SLM_EXIT_CL
SLM_EXIT_IN = cvar.SLM_EXIT_IN
SLM_EXIT_OUT = cvar.SLM_EXIT_OUT
SLM_FUNNEL_CL = cvar.SLM_FUNNEL_CL
SLM_FUNNEL_IN = cvar.SLM_FUNNEL_IN
SLM_FUNNEL_OUT = cvar.SLM_FUNNEL_OUT
SLM_OBA_GATE = cvar.SLM_OBA_GATE
SLM_QUAD_BIAS = cvar.SLM_QUAD_BIAS
SLM_RF_BOTTOM_DRIVE = cvar.SLM_RF_BOTTOM_DRIVE
SLM_RF_BOTTOM_FREQ = cvar.SLM_RF_BOTTOM_FREQ
SLM_RF_BOTTOM_NEG = cvar.SLM_RF_BOTTOM_NEG
SLM_RF_BOTTOM_POS = cvar.SLM_RF_BOTTOM_POS
SLM_RF_BOTTOM_POWER = cvar.SLM_RF_BOTTOM_POWER
SLM_RF_FUNNEL_DRIVE = cvar.SLM_RF_FUNNEL_DRIVE
SLM_RF_FUNNEL_FREQ = cvar.SLM_RF_FUNNEL_FREQ
SLM_RF_FUNNEL_NEG = cvar.SLM_RF_FUNNEL_NEG
SLM_RF_FUNNEL_POS = cvar.SLM_RF_FUNNEL_POS
SLM_RF_QUAD_DRIVE = cvar.SLM_RF_QUAD_DRIVE
SLM_RF_QUAD_FREQ = cvar.SLM_RF_QUAD_FREQ
SLM_RF_QUAD_NEG = cvar.SLM_RF_QUAD_NEG
SLM_RF_QUAD_POS = cvar.SLM_RF_QUAD_POS
SLM_QUAD_POWER = cvar.SLM_QUAD_POWER
SLM_RF_TOP_DRIVE = cvar.SLM_RF_TOP_DRIVE
SLM_RF_TOP_FREQ = cvar.SLM_RF_TOP_FREQ
SLM_RF_TOP_NEG = cvar.SLM_RF_TOP_NEG
SLM_RF_TOP_POS = cvar.SLM_RF_TOP_POS
SLM_RF_TOP_POWER = cvar.SLM_RF_TOP_POWER
SLM_SLIM_BIAS = cvar.SLM_SLIM_BIAS
SLM_SLIM_OFFSET = cvar.SLM_SLIM_OFFSET
SLM_TW_OBA_AMP = cvar.SLM_TW_OBA_AMP
SLM_TW_OBA_AUX = cvar.SLM_TW_OBA_AUX
SLM_TW_OBA_DIR = cvar.SLM_TW_OBA_DIR
SLM_TW_OBA_FREQ = cvar.SLM_TW_OBA_FREQ
SLM_TW_OBA_OFFSET = cvar.SLM_TW_OBA_OFFSET
SLM_TW_OBA_WAVEFORM = cvar.SLM_TW_OBA_WAVEFORM
SLM_TW_SEP_AMP = cvar.SLM_TW_SEP_AMP
SLM_TW_SEP_AUX = cvar.SLM_TW_SEP_AUX
SLM_TW_SEP_DIR = cvar.SLM_TW_SEP_DIR
SLM_TW_SEP_FREQ = cvar.SLM_TW_SEP_FREQ
SLM_TW_SEP_OFFSET = cvar.SLM_TW_SEP_OFFSET
SLM_TW_SEP_WAVEFORM = cvar.SLM_TW_SEP_WAVEFORM
SLM_TW_WASTE_AMP = cvar.SLM_TW_WASTE_AMP
SLM_TW_WASTE_AUX = cvar.SLM_TW_WASTE_AUX
SLM_TW_WASTE_DIR = cvar.SLM_TW_WASTE_DIR
SLM_TW_WASTE_FREQ = cvar.SLM_TW_WASTE_FREQ
SLM_TW_WASTE_OFFSET = cvar.SLM_TW_WASTE_OFFSET
SLM_TW_WASTE_WAVEFORM = cvar.SLM_TW_WASTE_WAVEFORM
HI_LO_FRAG = cvar.HI_LO_FRAG
SLOPE = cvar.SLOPE
INTERCEPT = cvar.INTERCEPT
RESIDUAL_FIT = cvar.RESIDUAL_FIT
TYPE = cvar.TYPE
COEFFICIENTS = cvar.COEFFICIENTS
CSS_COEFFICIENTS_HRIM = cvar.CSS_COEFFICIENTS_HRIM
AT_COEFFICIENTS = cvar.AT_COEFFICIENTS
MZ_COEFFICIENTS = cvar.MZ_COEFFICIENTS
POLYNOMIAL = cvar.POLYNOMIAL
UNKNOWN = cvar.UNKNOWN
PEAKS = cvar.PEAKS
CSS_COEFFICIENTS = cvar.CSS_COEFFICIENTS
MIN_CCS = cvar.MIN_CCS
MAX_CCS = cvar.MAX_CCS
CCS_DEGREE = cvar.CCS_DEGREE
CCS_AT_SURF = cvar.CCS_AT_SURF
CCS_CCAPS = cvar.CCS_CCAPS
GAS_TYPE = cvar.GAS_TYPE
CCS_GAS_MASS = cvar.CCS_GAS_MASS
VERSION = cvar.VERSION
ACQ_AGT_FILEPATH = cvar.ACQ_AGT_FILEPATH
ACQ_BOARD_TEMP = cvar.ACQ_BOARD_TEMP
ACQ_COLLECTION_MODE = cvar.ACQ_COLLECTION_MODE
ACQ_COMMENTS = cvar.ACQ_COMMENTS
ACQ_LC_MODEL = cvar.ACQ_LC_MODEL
ACQ_MS_LEVEL = cvar.ACQ_MS_LEVEL
ACQ_MS_METHOD = cvar.ACQ_MS_METHOD
ACQ_MS_MODEL = cvar.ACQ_MS_MODEL
ACQ_NUM_FRAMES = cvar.ACQ_NUM_FRAMES
ACQ_SLIM_METHOD = cvar.ACQ_SLIM_METHOD
ACQ_SLIM_MODEL = cvar.ACQ_SLIM_MODEL
ACQ_SLIM_PATH_LENGTH = cvar.ACQ_SLIM_PATH_LENGTH
ACQ_SOFTWARE_VERSION = cvar.ACQ_SOFTWARE_VERSION
ACQ_TAGS = cvar.ACQ_TAGS
ACQ_TEMPERATURE_CORRECTION = cvar.ACQ_TEMPERATURE_CORRECTION
ACQ_TIMESTAMP = cvar.ACQ_TIMESTAMP
ACQ_TUNE_FILE = cvar.ACQ_TUNE_FILE
ACQ_TYPE = cvar.ACQ_TYPE
ACQ_VENDOR_METADATA = cvar.ACQ_VENDOR_METADATA
ADC_AVG_MODE_ENABLE = cvar.ADC_AVG_MODE_ENABLE
ADC_AVG_MODE_FREQUENCY = cvar.ADC_AVG_MODE_FREQUENCY
ADC_AVG_MODE_RESCALE = cvar.ADC_AVG_MODE_RESCALE
ADC_BASELINE_STABILIZE_ENABLE = cvar.ADC_BASELINE_STABILIZE_ENABLE
ADC_BASELINE_STABILIZE_MODE = cvar.ADC_BASELINE_STABILIZE_MODE
ADC_CHANNEL = cvar.ADC_CHANNEL
ADC_COUPLING = cvar.ADC_COUPLING
ADC_DIGITAL_OFFSET = cvar.ADC_DIGITAL_OFFSET
ADC_DRIVER_REV = cvar.ADC_DRIVER_REV
ADC_FIRMWARE_REV = cvar.ADC_FIRMWARE_REV
ADC_MASS_SPEC_RANGE = cvar.ADC_MASS_SPEC_RANGE
ADC_MIN_NANOSECONDS = cvar.ADC_MIN_NANOSECONDS
ADC_MODEL = cvar.ADC_MODEL
ADC_OFFSET = cvar.ADC_OFFSET
ADC_PULSE_POLARITY = cvar.ADC_PULSE_POLARITY
ADC_PULSE_THRESHOLD = cvar.ADC_PULSE_THRESHOLD
ADC_RANGE = cvar.ADC_RANGE
ADC_RECORD_SIZE = cvar.ADC_RECORD_SIZE
ADC_REDUCTION_MODE = cvar.ADC_REDUCTION_MODE
ADC_SAMPLE_RATE = cvar.ADC_SAMPLE_RATE
ADC_SELF_TRIGGER_DUTY_CYCLE = cvar.ADC_SELF_TRIGGER_DUTY_CYCLE
ADC_SELF_TRIGGER_ENABLE = cvar.ADC_SELF_TRIGGER_ENABLE
ADC_SELF_TRIGGER_FREQUENCY = cvar.ADC_SELF_TRIGGER_FREQUENCY
ADC_SELF_TRIGGER_POLARITY = cvar.ADC_SELF_TRIGGER_POLARITY
ADC_STREAMING_MODE = cvar.ADC_STREAMING_MODE
ADC_ZA_HYSTERESIS = cvar.ADC_ZA_HYSTERESIS
ADC_ZA_POSTGATE_SAMPLES = cvar.ADC_ZA_POSTGATE_SAMPLES
ADC_ZA_PREGATE_SAMPLES = cvar.ADC_ZA_PREGATE_SAMPLES
ADC_ZA_THRESHOLD = cvar.ADC_ZA_THRESHOLD
ADC_ZERO_VALUE = cvar.ADC_ZERO_VALUE
CAL_CCS = cvar.CAL_CCS
GAS_MASS = cvar.GAS_MASS
MERGED_FILE = cvar.MERGED_FILE
READINGS = cvar.READINGS
SMP_AMOUNT = cvar.SMP_AMOUNT
SMP_AMOUNT_UNIT = cvar.SMP_AMOUNT_UNIT
SMP_BALANCE_TYPE = cvar.SMP_BALANCE_TYPE
SMP_CONCENTRATION = cvar.SMP_CONCENTRATION
SMP_CONCENTRATION_UNIT = cvar.SMP_CONCENTRATION_UNIT
SMP_DILUTION_FACTOR = cvar.SMP_DILUTION_FACTOR
SMP_INJECTION_VOLUME = cvar.SMP_INJECTION_VOLUME
SMP_MOLECULE_CLASS = cvar.SMP_MOLECULE_CLASS
SMP_NAME = cvar.SMP_NAME
SMP_PLATE_CODE = cvar.SMP_PLATE_CODE
SMP_PLATE_POSITION = cvar.SMP_PLATE_POSITION
SMP_POSITION = cvar.SMP_POSITION
SMP_RACK_CODE = cvar.SMP_RACK_CODE
SMP_SOLVENT = cvar.SMP_SOLVENT
SMP_TYPE = cvar.SMP_TYPE
STITCHED_FILE = cvar.STITCHED_FILE
USR_GROUP = cvar.USR_GROUP
USR_ROLE = cvar.USR_ROLE
USR_USERNAME = cvar.USR_USERNAME
GMD_CAL_DT_POLYNOMIAL = cvar.GMD_CAL_DT_POLYNOMIAL
GMD_CAL_DT_POWER_FLAGS = cvar.GMD_CAL_DT_POWER_FLAGS
GMD_CAL_DT_TRADITIONAL = cvar.GMD_CAL_DT_TRADITIONAL
GMD_CAL_MS_POLYNOMIAL = cvar.GMD_CAL_MS_POLYNOMIAL
GMD_CAL_MS_POWER_FLAGS = cvar.GMD_CAL_MS_POWER_FLAGS
GMD_CAL_MS_TRADITIONAL = cvar.GMD_CAL_MS_TRADITIONAL
GMD_FRM_FRAG_ENERGY_MODE = cvar.GMD_FRM_FRAG_ENERGY_MODE
GMD_FRM_FRAG_OP_MODE = cvar.GMD_FRM_FRAG_OP_MODE
GMD_FRM_INTENSITY_LIMIT = cvar.GMD_FRM_INTENSITY_LIMIT
GMD_FRM_METHOD_STATE = cvar.GMD_FRM_METHOD_STATE
GMD_FRM_MUX_GATE = cvar.GMD_FRM_MUX_GATE
GMD_FRM_MUX_SEQUENCE = cvar.GMD_FRM_MUX_SEQUENCE
GMD_FRM_NUM_MICROFRAMES = cvar.GMD_FRM_NUM_MICROFRAMES
GMD_FRM_POLARITY = cvar.GMD_FRM_POLARITY
GMD_FRM_TIMIING_INTENTS = cvar.GMD_FRM_TIMIING_INTENTS
GMD_KEY_FRAG = cvar.GMD_KEY_FRAG
GMD_SLIM_RF_FUNNEL_POWER = cvar.GMD_SLIM_RF_FUNNEL_POWER
GMD_SLM_ENTRANCE_OFFSET = cvar.GMD_SLM_ENTRANCE_OFFSET
GMD_SLM_EXIT_CL = cvar.GMD_SLM_EXIT_CL
GMD_SLM_EXIT_IN = cvar.GMD_SLM_EXIT_IN
GMD_SLM_EXIT_OUT = cvar.GMD_SLM_EXIT_OUT
GMD_SLM_FUNNEL_CL = cvar.GMD_SLM_FUNNEL_CL
GMD_SLM_FUNNEL_IN = cvar.GMD_SLM_FUNNEL_IN
GMD_SLM_FUNNEL_OUT = cvar.GMD_SLM_FUNNEL_OUT
GMD_SLM_OBA_GATE = cvar.GMD_SLM_OBA_GATE
GMD_SLM_QUAD_BIAS = cvar.GMD_SLM_QUAD_BIAS
GMD_SLM_RF_BOTTOM_DRIVE = cvar.GMD_SLM_RF_BOTTOM_DRIVE
GMD_SLM_RF_BOTTOM_FREQ = cvar.GMD_SLM_RF_BOTTOM_FREQ
GMD_SLM_RF_BOTTOM_NEG = cvar.GMD_SLM_RF_BOTTOM_NEG
GMD_SLM_RF_BOTTOM_POS = cvar.GMD_SLM_RF_BOTTOM_POS
GMD_SLM_RF_BOTTOM_POWER = cvar.GMD_SLM_RF_BOTTOM_POWER
GMD_SLM_RF_FUNNEL_DRIVE = cvar.GMD_SLM_RF_FUNNEL_DRIVE
GMD_SLM_RF_FUNNEL_FREQ = cvar.GMD_SLM_RF_FUNNEL_FREQ
GMD_SLM_RF_FUNNEL_NEG = cvar.GMD_SLM_RF_FUNNEL_NEG
GMD_SLM_RF_FUNNEL_POS = cvar.GMD_SLM_RF_FUNNEL_POS
GMD_SLM_RF_QUAD_DRIVE = cvar.GMD_SLM_RF_QUAD_DRIVE
GMD_SLM_RF_QUAD_FREQ = cvar.GMD_SLM_RF_QUAD_FREQ
GMD_SLM_RF_QUAD_NEG = cvar.GMD_SLM_RF_QUAD_NEG
GMD_SLM_RF_QUAD_POS = cvar.GMD_SLM_RF_QUAD_POS
GMD_SLM_QUAD_POWER = cvar.GMD_SLM_QUAD_POWER
GMD_SLM_RF_TOP_DRIVE = cvar.GMD_SLM_RF_TOP_DRIVE
GMD_SLM_RF_TOP_FREQ = cvar.GMD_SLM_RF_TOP_FREQ
GMD_SLM_RF_TOP_NEG = cvar.GMD_SLM_RF_TOP_NEG
GMD_SLM_RF_TOP_POS = cvar.GMD_SLM_RF_TOP_POS
GMD_SLM_RF_TOP_POWER = cvar.GMD_SLM_RF_TOP_POWER
GMD_SLM_SLIM_BIAS = cvar.GMD_SLM_SLIM_BIAS
GMD_SLM_SLIM_OFFSET = cvar.GMD_SLM_SLIM_OFFSET
GMD_SLM_TW_OBA_AMP = cvar.GMD_SLM_TW_OBA_AMP
GMD_SLM_TW_OBA_AUX = cvar.GMD_SLM_TW_OBA_AUX
GMD_SLM_TW_OBA_DIR = cvar.GMD_SLM_TW_OBA_DIR
GMD_SLM_TW_OBA_FREQ = cvar.GMD_SLM_TW_OBA_FREQ
GMD_SLM_TW_OBA_OFFSET = cvar.GMD_SLM_TW_OBA_OFFSET
GMD_SLM_TW_OBA_WAVEFORM = cvar.GMD_SLM_TW_OBA_WAVEFORM
GMD_SLM_TW_SEP_AMP = cvar.GMD_SLM_TW_SEP_AMP
GMD_SLM_TW_SEP_AUX = cvar.GMD_SLM_TW_SEP_AUX
GMD_SLM_TW_SEP_DIR = cvar.GMD_SLM_TW_SEP_DIR
GMD_SLM_TW_SEP_FREQ = cvar.GMD_SLM_TW_SEP_FREQ
GMD_SLM_TW_SEP_OFFSET = cvar.GMD_SLM_TW_SEP_OFFSET
GMD_SLM_TW_SEP_WAVEFORM = cvar.GMD_SLM_TW_SEP_WAVEFORM
GMD_SLM_TW_WASTE_AMP = cvar.GMD_SLM_TW_WASTE_AMP
GMD_SLM_TW_WASTE_AUX = cvar.GMD_SLM_TW_WASTE_AUX
GMD_SLM_TW_WASTE_DIR = cvar.GMD_SLM_TW_WASTE_DIR
GMD_SLM_TW_WASTE_FREQ = cvar.GMD_SLM_TW_WASTE_FREQ
GMD_SLM_TW_WASTE_OFFSET = cvar.GMD_SLM_TW_WASTE_OFFSET
GMD_SLM_TW_WASTE_WAVEFORM = cvar.GMD_SLM_TW_WASTE_WAVEFORM
NANOSECONDS_PER_SECOND = cvar.NANOSECONDS_PER_SECOND
MICROSECONDS_PER_SECOND = cvar.MICROSECONDS_PER_SECOND
MILLISECONDS_PER_SECOND = cvar.MILLISECONDS_PER_SECOND
READONLY = cvar.READONLY
WRITE = cvar.WRITE
APPEND = cvar.APPEND

class GlobalMetadata(Metadata):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mbisdk.GlobalMetadata_swiginit(self, _mbisdk.new_GlobalMetadata())
    __swig_destroy__ = _mbisdk.delete_GlobalMetadata

# Register GlobalMetadata in _mbisdk:
_mbisdk.GlobalMetadata_swigregister(GlobalMetadata)
class FrameMetadata(Metadata):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mbisdk.FrameMetadata_swiginit(self, _mbisdk.new_FrameMetadata())
    __swig_destroy__ = _mbisdk.delete_FrameMetadata

# Register FrameMetadata in _mbisdk:
_mbisdk.FrameMetadata_swigregister(FrameMetadata)
class FragmentationMetadata(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    eType_NONE = _mbisdk.FragmentationMetadata_eType_NONE
    eType_HILO = _mbisdk.FragmentationMetadata_eType_HILO

    def __init__(self):
        _mbisdk.FragmentationMetadata_swiginit(self, _mbisdk.new_FragmentationMetadata())
    type = property(_mbisdk.FragmentationMetadata_type_get, _mbisdk.FragmentationMetadata_type_set)
    frag_energy = property(_mbisdk.FragmentationMetadata_frag_energy_get, _mbisdk.FragmentationMetadata_frag_energy_set)
    __swig_destroy__ = _mbisdk.delete_FragmentationMetadata

# Register FragmentationMetadata in _mbisdk:
_mbisdk.FragmentationMetadata_swigregister(FragmentationMetadata)
class MassSpectrum(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    intensities = property(_mbisdk.MassSpectrum_intensities_get, _mbisdk.MassSpectrum_intensities_set)
    indices = property(_mbisdk.MassSpectrum_indices_get, _mbisdk.MassSpectrum_indices_set)
    mz = property(_mbisdk.MassSpectrum_mz_get, _mbisdk.MassSpectrum_mz_set)
    isZeroPadded = property(_mbisdk.MassSpectrum_isZeroPadded_get, _mbisdk.MassSpectrum_isZeroPadded_set)
    nnz = property(_mbisdk.MassSpectrum_nnz_get, _mbisdk.MassSpectrum_nnz_set)

    def __init__(self):
        _mbisdk.MassSpectrum_swiginit(self, _mbisdk.new_MassSpectrum())
    __swig_destroy__ = _mbisdk.delete_MassSpectrum

# Register MassSpectrum in _mbisdk:
_mbisdk.MassSpectrum_swigregister(MassSpectrum)
class Frame(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.Frame_swiginit(self, _mbisdk.new_Frame(*args))

    def IsLoaded(self):
        return _mbisdk.Frame_IsLoaded(self)

    def LoadMetadata(self, metadata):
        return _mbisdk.Frame_LoadMetadata(self, metadata)

    def Load(self, *args):
        return _mbisdk.Frame_Load(self, *args)

    def Unload(self):
        return _mbisdk.Frame_Unload(self)

    def GetNonZeroScanIndices(self):
        return _mbisdk.Frame_GetNonZeroScanIndices(self)

    def GetFrameTotalIntensity(self):
        return _mbisdk.Frame_GetFrameTotalIntensity(self)

    def GetScanTotalIntensity(self, scanIndex):
        return _mbisdk.Frame_GetScanTotalIntensity(self, scanIndex)

    def GetMaxPointsInScan(self):
        return _mbisdk.Frame_GetMaxPointsInScan(self)

    def GetCalibration(self):
        return _mbisdk.Frame_GetCalibration(self)

    def isFragmentationData(self):
        return _mbisdk.Frame_isFragmentationData(self)

    def Time(self):
        return _mbisdk.Frame_Time(self)

    def GetNumScans(self):
        return _mbisdk.Frame_GetNumScans(self)

    def GetIonPolarity(self):
        return _mbisdk.Frame_GetIonPolarity(self)

    def GetFrameDataAsCOOArray(self, *args):
        return _mbisdk.Frame_GetFrameDataAsCOOArray(self, *args)

    def GetFrameDataAsCSRArray(self, *args):
        return _mbisdk.Frame_GetFrameDataAsCSRArray(self, *args)

    def GetFrameIMMSSpectrumAsCSR(self, *args):
        return _mbisdk.Frame_GetFrameIMMSSpectrumAsCSR(self, *args)

    def GetFrameIMMSSpectrumAsCOO(self, *args):
        return _mbisdk.Frame_GetFrameIMMSSpectrumAsCOO(self, *args)

    def GetFrameDataAsCSRComponents(self):
        return _mbisdk.Frame_GetFrameDataAsCSRComponents(self)

    def GetScanDataMzIndexedSparse(self, *args):
        return _mbisdk.Frame_GetScanDataMzIndexedSparse(self, *args)

    def GetScanDataMzIndexedDense(self, scanIndex):
        return _mbisdk.Frame_GetScanDataMzIndexedDense(self, scanIndex)

    def GetMassSpectrum(self, *args):
        return _mbisdk.Frame_GetMassSpectrum(self, *args)

    def GetScan(self, *args):
        return _mbisdk.Frame_GetScan(self, *args)

    def GetScanDataToFIndexedSparse(self, *args):
        return _mbisdk.Frame_GetScanDataToFIndexedSparse(self, *args)

    def GetScanDataToFIndexedDense(self, scanIndex):
        return _mbisdk.Frame_GetScanDataToFIndexedDense(self, scanIndex)

    def getFrameMetaDataItem(self, key):
        return _mbisdk.Frame_getFrameMetaDataItem(self, key)

    def GetScanSummationToFIndexedDense(self, intensityOut, minToFIndex, minToFScanIndex, maxToFIndex, maxToFScanIndex):
        return _mbisdk.Frame_GetScanSummationToFIndexedDense(self, intensityOut, minToFIndex, minToFScanIndex, maxToFIndex, maxToFScanIndex)

    def GetScanDefinition(self):
        return _mbisdk.Frame_GetScanDefinition(self)

    def HasScanDefinition(self):
        return _mbisdk.Frame_HasScanDefinition(self)

    def GetArrivalBinWidth(self):
        return _mbisdk.Frame_GetArrivalBinWidth(self)

    def GetArrivalBinTimeOffset(self, binIndex):
        return _mbisdk.Frame_GetArrivalBinTimeOffset(self, binIndex)

    def GetArrivalBinIndex(self, timeOffset):
        return _mbisdk.Frame_GetArrivalBinIndex(self, timeOffset)

    def GetToFOffset(self):
        return _mbisdk.Frame_GetToFOffset(self)

    def GetToFLength(self):
        return _mbisdk.Frame_GetToFLength(self)

    def GetArrivalBinOffset(self):
        return _mbisdk.Frame_GetArrivalBinOffset(self)

    def GetArrivalBinLength(self):
        return _mbisdk.Frame_GetArrivalBinLength(self)

    def GetGenericMetaData(self, strKey):
        return _mbisdk.Frame_GetGenericMetaData(self, strKey)

    def GetGenericMetaDataInt(self, strKey):
        return _mbisdk.Frame_GetGenericMetaDataInt(self, strKey)

    def GetGenericMetaDataDouble(self, strKey):
        return _mbisdk.Frame_GetGenericMetaDataDouble(self, strKey)

    def GetATTicList(self):
        return _mbisdk.Frame_GetATTicList(self)

    def GetATTicItem(self, nIndex):
        return _mbisdk.Frame_GetATTicItem(self, nIndex)

    def GetSampleIntensities(self):
        return _mbisdk.Frame_GetSampleIntensities(self)

    def GetDataCountItem(self, nIndex):
        return _mbisdk.Frame_GetDataCountItem(self, nIndex)

    def GetGates(self):
        return _mbisdk.Frame_GetGates(self)

    def GetDataPositionItemFirst(self, nIndex):
        return _mbisdk.Frame_GetDataPositionItemFirst(self, nIndex)

    def GetDataPositionItemSecond(self, nIndex):
        return _mbisdk.Frame_GetDataPositionItemSecond(self, nIndex)

    def GetSampleOffsets(self):
        return _mbisdk.Frame_GetSampleOffsets(self)

    def GetIndexCountItem(self, nIndex):
        return _mbisdk.Frame_GetIndexCountItem(self, nIndex)

    def GetGateIndexOffsets(self):
        return _mbisdk.Frame_GetGateIndexOffsets(self)

    def GetIndexPositionItem(self, nIndex):
        return _mbisdk.Frame_GetIndexPositionItem(self, nIndex)

    def GetTriggerTimeStamps(self):
        return _mbisdk.Frame_GetTriggerTimeStamps(self)

    def GetTriggerTimeStampItem(self, nIndex):
        return _mbisdk.Frame_GetTriggerTimeStampItem(self, nIndex)

    def GetFrameMetaData(self):
        return _mbisdk.Frame_GetFrameMetaData(self)

    def GetCollisionEnergy(self):
        return _mbisdk.Frame_GetCollisionEnergy(self)

    def IsCollisionEnergyValid(self):
        return _mbisdk.Frame_IsCollisionEnergyValid(self)

    def HasFixedCE(self):
        return _mbisdk.Frame_HasFixedCE(self)

    def GetCE(self, scanIndex):
        return _mbisdk.Frame_GetCE(self, scanIndex)

    def GetCEByTime(self, scanTime):
        return _mbisdk.Frame_GetCEByTime(self, scanTime)

    def GetIsolationWindowStartByTime(self, scanTime):
        return _mbisdk.Frame_GetIsolationWindowStartByTime(self, scanTime)

    def GetIsolationWindowEndByTime(self, scanTime):
        return _mbisdk.Frame_GetIsolationWindowEndByTime(self, scanTime)

    def GetCEByIndex(self, scanIndex):
        return _mbisdk.Frame_GetCEByIndex(self, scanIndex)

    def GetIsolationWindowStartByIndex(self, scanIndex):
        return _mbisdk.Frame_GetIsolationWindowStartByIndex(self, scanIndex)

    def GetIsolationWindowEndByIndex(self, scanIndex):
        return _mbisdk.Frame_GetIsolationWindowEndByIndex(self, scanIndex)

    def GetPartition(self):
        return _mbisdk.Frame_GetPartition(self)

    def GetPartitionSP(self):
        return _mbisdk.Frame_GetPartitionSP(self)

    def GetErrorOutput(self):
        return _mbisdk.Frame_GetErrorOutput(self)
    FRAME_CE_PARSE_ERROR_HEADER = _mbisdk.Frame_FRAME_CE_PARSE_ERROR_HEADER
    FRAME_CE_PARSE_INVALID_DATA = _mbisdk.Frame_FRAME_CE_PARSE_INVALID_DATA
    FRAME_CE_PARSE_BAD_FRAG_DATA = _mbisdk.Frame_FRAME_CE_PARSE_BAD_FRAG_DATA
    FRAME_CE_PARSE_MISSING_DATA = _mbisdk.Frame_FRAME_CE_PARSE_MISSING_DATA
    __swig_destroy__ = _mbisdk.delete_Frame

# Register Frame in _mbisdk:
_mbisdk.Frame_swigregister(Frame)
class MBIFile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ExperimentType_MS1 = _mbisdk.MBIFile_ExperimentType_MS1
    ExperimentType_AIF = _mbisdk.MBIFile_ExperimentType_AIF
    ExperimentType_SIFF_MAF = _mbisdk.MBIFile_ExperimentType_SIFF_MAF
    ExperimentType_MIFF_MAF = _mbisdk.MBIFile_ExperimentType_MIFF_MAF
    ERR_UNEXPECTED = _mbisdk.MBIFile_ERR_UNEXPECTED
    ERR_SUCCESS = _mbisdk.MBIFile_ERR_SUCCESS
    ERR_FILE_NOT_FOUND = _mbisdk.MBIFile_ERR_FILE_NOT_FOUND
    ERR_HDF5_FILE_ERROR = _mbisdk.MBIFile_ERR_HDF5_FILE_ERROR
    ERR_FILE_NOT_INITIALIZED = _mbisdk.MBIFile_ERR_FILE_NOT_INITIALIZED
    ERR_METADATA_NOT_LOADED = _mbisdk.MBIFile_ERR_METADATA_NOT_LOADED
    ERR_FRAME_NOT_LOADED = _mbisdk.MBIFile_ERR_FRAME_NOT_LOADED
    ERR_DOUBLE_LOAD = _mbisdk.MBIFile_ERR_DOUBLE_LOAD
    ERR_BAD_FRAME_INDEX = _mbisdk.MBIFile_ERR_BAD_FRAME_INDEX
    ERR_BAD_SCAN_INDEX = _mbisdk.MBIFile_ERR_BAD_SCAN_INDEX
    ERR_ITEM_MISSING = _mbisdk.MBIFile_ERR_ITEM_MISSING
    ERR_OPERATION_NOT_SUPPORTED = _mbisdk.MBIFile_ERR_OPERATION_NOT_SUPPORTED
    ERR_ZERO_FRAMES = _mbisdk.MBIFile_ERR_ZERO_FRAMES

    def __init__(self, *args):
        _mbisdk.MBIFile_swiginit(self, _mbisdk.new_MBIFile(*args))

    def Close(self):
        return _mbisdk.MBIFile_Close(self)

    def GetMaxScansInFrame(self, nFrame):
        return _mbisdk.MBIFile_GetMaxScansInFrame(self, nFrame)

    def SetGlobalMetaData(self, globalMetadata):
        return _mbisdk.MBIFile_SetGlobalMetaData(self, globalMetadata)

    def GetCalibration(self):
        return _mbisdk.MBIFile_GetCalibration(self)

    def HasCCSCalibration(self):
        return _mbisdk.MBIFile_HasCCSCalibration(self)

    def GetEyeOnCCSCalibration(self):
        return _mbisdk.MBIFile_GetEyeOnCCSCalibration(self)

    def GetCCSCalibration(self, coefficients):
        return _mbisdk.MBIFile_GetCCSCalibration(self, coefficients)

    def GetExperimentType(self):
        return _mbisdk.MBIFile_GetExperimentType(self)

    def NumFrames(self):
        return _mbisdk.MBIFile_NumFrames(self)

    def GetFrames(self):
        return _mbisdk.MBIFile_GetFrames(self)

    def GetFrame(self, frameIndex):
        return _mbisdk.MBIFile_GetFrame(self, frameIndex)

    def GetFrameMetadata(self, frameIndex):
        return _mbisdk.MBIFile_GetFrameMetadata(self, frameIndex)

    def GetAcquisitionTimestamp(self):
        return _mbisdk.MBIFile_GetAcquisitionTimestamp(self)

    def GetRetentionTimes(self):
        return _mbisdk.MBIFile_GetRetentionTimes(self)

    def GetFrameMSLevels(self):
        return _mbisdk.MBIFile_GetFrameMSLevels(self)

    def GetFrameIonPolarities(self):
        return _mbisdk.MBIFile_GetFrameIonPolarities(self)

    def GetIonPolarity(self):
        return _mbisdk.MBIFile_GetIonPolarity(self)

    def GetFrameCollisionEnergies(self):
        return _mbisdk.MBIFile_GetFrameCollisionEnergies(self)

    def GetUpperMZBounds(self):
        return _mbisdk.MBIFile_GetUpperMZBounds(self)

    def GetScanCounts(self):
        return _mbisdk.MBIFile_GetScanCounts(self)

    def GetAverageIMSamplingPeriod(self):
        return _mbisdk.MBIFile_GetAverageIMSamplingPeriod(self)

    def GetMaxNumScansPerFrame(self):
        return _mbisdk.MBIFile_GetMaxNumScansPerFrame(self)

    def NumScanDefinitions(self):
        return _mbisdk.MBIFile_NumScanDefinitions(self)

    def LoadFrameData(self, frameIndex):
        return _mbisdk.MBIFile_LoadFrameData(self, frameIndex)

    def UnloadFrame(self, frameIndex):
        return _mbisdk.MBIFile_UnloadFrame(self, frameIndex)

    def UncacheFrame(self, frameIndex):
        return _mbisdk.MBIFile_UncacheFrame(self, frameIndex)

    def GetMaxPointsInScan(self):
        return _mbisdk.MBIFile_GetMaxPointsInScan(self)

    def GetFilename(self):
        return _mbisdk.MBIFile_GetFilename(self)

    def SetFilename(self, path):
        return _mbisdk.MBIFile_SetFilename(self, path)

    def SetAccessMode(self, accessMode):
        return _mbisdk.MBIFile_SetAccessMode(self, accessMode)

    def GetRtTic(self, frameIndex):
        return _mbisdk.MBIFile_GetRtTic(self, frameIndex)

    def CheckFrameIndex(self, nFrameIndex):
        return _mbisdk.MBIFile_CheckFrameIndex(self, nFrameIndex)

    def GetFrameStartTime(self, pFrameMD):
        return _mbisdk.MBIFile_GetFrameStartTime(self, pFrameMD)

    def loadAtTic(self, frameIndex):
        return _mbisdk.MBIFile_loadAtTic(self, frameIndex)

    def Init(self):
        return _mbisdk.MBIFile_Init(self)

    def GetErrorCode(self):
        return _mbisdk.MBIFile_GetErrorCode(self)

    def GetErrorMessage(self):
        return _mbisdk.MBIFile_GetErrorMessage(self)

    def GetSampleRate(self):
        return _mbisdk.MBIFile_GetSampleRate(self)

    def GetNumFrames(self):
        return _mbisdk.MBIFile_GetNumFrames(self)

    def GetVersion(self):
        return _mbisdk.MBIFile_GetVersion(self)

    def GetGlobalMetaData(self):
        return _mbisdk.MBIFile_GetGlobalMetaData(self)

    def IsInitialized(self):
        return _mbisdk.MBIFile_IsInitialized(self)

    def GetToFOffset(self):
        return _mbisdk.MBIFile_GetToFOffset(self)

    def GetToFLength(self):
        return _mbisdk.MBIFile_GetToFLength(self)

    def GetArrivalBinOffset(self):
        return _mbisdk.MBIFile_GetArrivalBinOffset(self)

    def GetArrivalBinLength(self):
        return _mbisdk.MBIFile_GetArrivalBinLength(self)

    def GetSpecificRtTicValue(self, nFrameIndex):
        return _mbisdk.MBIFile_GetSpecificRtTicValue(self, nFrameIndex)

    def GetRtTicList(self):
        return _mbisdk.MBIFile_GetRtTicList(self)

    def GetFrameTIC(self):
        return _mbisdk.MBIFile_GetFrameTIC(self)

    def getMetaDataItem(self, key):
        return _mbisdk.MBIFile_getMetaDataItem(self, key)

    def getMetaDataItemInt(self, key):
        return _mbisdk.MBIFile_getMetaDataItemInt(self, key)

    def getMetaDataItemDouble(self, key):
        return _mbisdk.MBIFile_getMetaDataItemDouble(self, key)

    def setExternalErrorMessage(self, input_str):
        return _mbisdk.MBIFile_setExternalErrorMessage(self, input_str)

    def getExternalErrorMessage(self):
        return _mbisdk.MBIFile_getExternalErrorMessage(self)

    def HasScanDefinitions(self):
        return _mbisdk.MBIFile_HasScanDefinitions(self)

    def GetIsolationStart(self, frameIndex, t):
        return _mbisdk.MBIFile_GetIsolationStart(self, frameIndex, t)

    def GetIsolationEnd(self, frameIndex, t):
        return _mbisdk.MBIFile_GetIsolationEnd(self, frameIndex, t)
    __swig_destroy__ = _mbisdk.delete_MBIFile

# Register MBIFile in _mbisdk:
_mbisdk.MBIFile_swigregister(MBIFile)
class CalPolynomial(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, coefficients):
        _mbisdk.CalPolynomial_swiginit(self, _mbisdk.new_CalPolynomial(coefficients))

    def YFromX(self, x):
        return _mbisdk.CalPolynomial_YFromX(self, x)

    def DerivativeAtX(self, x):
        return _mbisdk.CalPolynomial_DerivativeAtX(self, x)

    def GetDegree(self):
        return _mbisdk.CalPolynomial_GetDegree(self)
    __swig_destroy__ = _mbisdk.delete_CalPolynomial

# Register CalPolynomial in _mbisdk:
_mbisdk.CalPolynomial_swigregister(CalPolynomial)
ATTEMPT_MAX = cvar.ATTEMPT_MAX
TOLERANCE = cvar.TOLERANCE

class CCSBisectionSearch(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, CCSpolymonial):
        _mbisdk.CCSBisectionSearch_swiginit(self, _mbisdk.new_CCSBisectionSearch(CCSpolymonial))

    def Search(self):
        return _mbisdk.CCSBisectionSearch_Search(self)

    def NewEpsilion(self, epsilon):
        return _mbisdk.CCSBisectionSearch_NewEpsilion(self, epsilon)

    def NewTarget(self, target):
        return _mbisdk.CCSBisectionSearch_NewTarget(self, target)

    def getEpsilon(self):
        return _mbisdk.CCSBisectionSearch_getEpsilon(self)
    __swig_destroy__ = _mbisdk.delete_CCSBisectionSearch

# Register CCSBisectionSearch in _mbisdk:
_mbisdk.CCSBisectionSearch_swigregister(CCSBisectionSearch)
class NewtonMethod(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, polynomial):
        _mbisdk.NewtonMethod_swiginit(self, _mbisdk.new_NewtonMethod(polynomial))

    def RootStartFromX(self, startingX):
        return _mbisdk.NewtonMethod_RootStartFromX(self, startingX)

    def isSuccess(self):
        return _mbisdk.NewtonMethod_isSuccess(self)
    __swig_destroy__ = _mbisdk.delete_NewtonMethod

# Register NewtonMethod in _mbisdk:
_mbisdk.NewtonMethod_swigregister(NewtonMethod)
class TofCalibration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.TofCalibration_swiginit(self, _mbisdk.new_TofCalibration(*args))

    def TofError(self, uSecTOF):
        return _mbisdk.TofCalibration_TofError(self, uSecTOF)

    def IndexToMicroseconds(self, index):
        return _mbisdk.TofCalibration_IndexToMicroseconds(self, index)

    def MicrosecondsToMz(self, uSec):
        return _mbisdk.TofCalibration_MicrosecondsToMz(self, uSec)

    def IndexToMz(self, *args):
        return _mbisdk.TofCalibration_IndexToMz(self, *args)

    def IndexToMzBuffer(self, indices, mzOut):
        return _mbisdk.TofCalibration_IndexToMzBuffer(self, indices, mzOut)

    def MicrosecondsToIndex(self, uSec):
        return _mbisdk.TofCalibration_MicrosecondsToIndex(self, uSec)

    def MzToMicroseconds(self, mz):
        return _mbisdk.TofCalibration_MzToMicroseconds(self, mz)

    def TotalPolynomial(self):
        return _mbisdk.TofCalibration_TotalPolynomial(self)

    def MzToIndex(self, mz):
        return _mbisdk.TofCalibration_MzToIndex(self, mz)

    def Slope(self):
        return _mbisdk.TofCalibration_Slope(self)

    def Intercept(self):
        return _mbisdk.TofCalibration_Intercept(self)

    def ResidualFit(self):
        return _mbisdk.TofCalibration_ResidualFit(self)

    def getFailureStatus(self):
        return _mbisdk.TofCalibration_getFailureStatus(self)

    def getStatusText(self):
        return _mbisdk.TofCalibration_getStatusText(self)
    slope = property(_mbisdk.TofCalibration_slope_get, _mbisdk.TofCalibration_slope_set)
    intercept = property(_mbisdk.TofCalibration_intercept_get, _mbisdk.TofCalibration_intercept_set)
    __swig_destroy__ = _mbisdk.delete_TofCalibration

# Register TofCalibration in _mbisdk:
_mbisdk.TofCalibration_swigregister(TofCalibration)
eCalibrationType_POLYNOMIAL = _mbisdk.eCalibrationType_POLYNOMIAL
eCalibrationType_UNKNOWN = _mbisdk.eCalibrationType_UNKNOWN
class CcsCalibration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Type(self):
        return _mbisdk.CcsCalibration_Type(self)

    def Coefficients(self):
        return _mbisdk.CcsCalibration_Coefficients(self)

    def __init__(self, *args):
        _mbisdk.CcsCalibration_swiginit(self, _mbisdk.new_CcsCalibration(*args))
    __swig_destroy__ = _mbisdk.delete_CcsCalibration

# Register CcsCalibration in _mbisdk:
_mbisdk.CcsCalibration_swigregister(CcsCalibration)
class GlobalCcsCalibration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.GlobalCcsCalibration_swiginit(self, _mbisdk.new_GlobalCcsCalibration(*args))

    def Type(self):
        return _mbisdk.GlobalCcsCalibration_Type(self)

    def Coefficients(self):
        return _mbisdk.GlobalCcsCalibration_Coefficients(self)

    def CSSCoefficients(self):
        return _mbisdk.GlobalCcsCalibration_CSSCoefficients(self)

    def MZCoefficients(self):
        return _mbisdk.GlobalCcsCalibration_MZCoefficients(self)

    def ATCoefficients(self):
        return _mbisdk.GlobalCcsCalibration_ATCoefficients(self)
    __swig_destroy__ = _mbisdk.delete_GlobalCcsCalibration

# Register GlobalCcsCalibration in _mbisdk:
_mbisdk.GlobalCcsCalibration_swigregister(GlobalCcsCalibration)
class EyeOnCcsCalibration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.EyeOnCcsCalibration_swiginit(self, _mbisdk.new_EyeOnCcsCalibration(*args))
    __swig_destroy__ = _mbisdk.delete_EyeOnCcsCalibration
    BAD_FILE_POINTER = _mbisdk.EyeOnCcsCalibration_BAD_FILE_POINTER
    BAD_FRAME_INDEX = _mbisdk.EyeOnCcsCalibration_BAD_FRAME_INDEX
    BAD_MASS_VALUE = _mbisdk.EyeOnCcsCalibration_BAD_MASS_VALUE
    BAD_CALC_VALUE = _mbisdk.EyeOnCcsCalibration_BAD_CALC_VALUE

    def ParseCCSCal(self, strCCSData):
        return _mbisdk.EyeOnCcsCalibration_ParseCCSCal(self, strCCSData)

    def GetCCSMinimum(self):
        return _mbisdk.EyeOnCcsCalibration_GetCCSMinimum(self)

    def GetCCSMaximum(self):
        return _mbisdk.EyeOnCcsCalibration_GetCCSMaximum(self)

    def GetDegree(self):
        return _mbisdk.EyeOnCcsCalibration_GetDegree(self)

    def GetAtSurf(self):
        return _mbisdk.EyeOnCcsCalibration_GetAtSurf(self)

    def GetCCSCoefficients(self):
        return _mbisdk.EyeOnCcsCalibration_GetCCSCoefficients(self)

    def SetCCSCoefficients(self, vec_input):
        return _mbisdk.EyeOnCcsCalibration_SetCCSCoefficients(self, vec_input)

    def ArrivalTimeToCCS(self, *args):
        return _mbisdk.EyeOnCcsCalibration_ArrivalTimeToCCS(self, *args)

    def GetCalibratedRange(self):
        return _mbisdk.EyeOnCcsCalibration_GetCalibratedRange(self)

    def CCSToArrivalTime(self, *args):
        return _mbisdk.EyeOnCcsCalibration_CCSToArrivalTime(self, *args)

    def GetErrorOutput(self):
        return _mbisdk.EyeOnCcsCalibration_GetErrorOutput(self)

    def UnReduceCCSValue(self, unadjusted_ccs, M_ion, Z):
        return _mbisdk.EyeOnCcsCalibration_UnReduceCCSValue(self, unadjusted_ccs, M_ion, Z)

    def ReduceCCSValue(self, ccs_value, M_ion, Z):
        return _mbisdk.EyeOnCcsCalibration_ReduceCCSValue(self, ccs_value, M_ion, Z)

    def ReductionFactor(self, M_ion, Z):
        return _mbisdk.EyeOnCcsCalibration_ReductionFactor(self, M_ion, Z)

    def ComputeGasMass(self, *args):
        return _mbisdk.EyeOnCcsCalibration_ComputeGasMass(self, *args)

    def GenerateThrownErrorMessage(self, error_type, frame_index=0, arrival_time=0.0):
        return _mbisdk.EyeOnCcsCalibration_GenerateThrownErrorMessage(self, error_type, frame_index, arrival_time)

    def IsValid(self, ptr):
        return _mbisdk.EyeOnCcsCalibration_IsValid(self, ptr)

    def SetGasMass(self, gas_mass_input):
        return _mbisdk.EyeOnCcsCalibration_SetGasMass(self, gas_mass_input)

    def GetGasMass(self):
        return _mbisdk.EyeOnCcsCalibration_GetGasMass(self)

    def GetTofCalibration(self):
        return _mbisdk.EyeOnCcsCalibration_GetTofCalibration(self)

    def ChooseGoodRoot(self, root_1, root_2, ion_mass):
        return _mbisdk.EyeOnCcsCalibration_ChooseGoodRoot(self, root_1, root_2, ion_mass)

    def GetVersion(self):
        return _mbisdk.EyeOnCcsCalibration_GetVersion(self)
    CCS_ERROR_HEADER = _mbisdk.EyeOnCcsCalibration_CCS_ERROR_HEADER
    CCS_MISSING_DATA = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_DATA
    CCS_INVALID_DATA = _mbisdk.EyeOnCcsCalibration_CCS_INVALID_DATA
    CCS_MISSING_CCS_COEFFICIENTS = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_CCS_COEFFICIENTS
    CCS_MISSING_MIN_CCS = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_MIN_CCS
    CCS_MISSING_MAX_CCS = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_MAX_CCS
    CCS_MISSING_CCS_DEGREE = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_CCS_DEGREE
    CCS_MISSING_CCS_AT_SURF = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_CCS_AT_SURF
    CCS_DEGREE_COEFFICIENTS_MISMATCH = _mbisdk.EyeOnCcsCalibration_CCS_DEGREE_COEFFICIENTS_MISMATCH
    CCS_BAD_FRAME_INDEX_HEADER = _mbisdk.EyeOnCcsCalibration_CCS_BAD_FRAME_INDEX_HEADER
    CCS_BAD_FRAME_INDEX_FOOTER = _mbisdk.EyeOnCcsCalibration_CCS_BAD_FRAME_INDEX_FOOTER
    CCS_BAD_FILE_POINTER = _mbisdk.EyeOnCcsCalibration_CCS_BAD_FILE_POINTER
    CCS_MISSING_TOF_CALIBRATION = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_TOF_CALIBRATION
    CCS_MISSING_CCS_GAS_TYPE = _mbisdk.EyeOnCcsCalibration_CCS_MISSING_CCS_GAS_TYPE
    CCS_BAD_GAS_MASS = _mbisdk.EyeOnCcsCalibration_CCS_BAD_GAS_MASS
    CCS_ARRIVAL_TIME_HEADER = _mbisdk.EyeOnCcsCalibration_CCS_ARRIVAL_TIME_HEADER
    CCS_BAD_MASS_VALUE_PART_2 = _mbisdk.EyeOnCcsCalibration_CCS_BAD_MASS_VALUE_PART_2
    CCS_BAD_ADJUSTMENT_PART_2 = _mbisdk.EyeOnCcsCalibration_CCS_BAD_ADJUSTMENT_PART_2

# Register EyeOnCcsCalibration in _mbisdk:
_mbisdk.EyeOnCcsCalibration_swigregister(EyeOnCcsCalibration)
class NonReducedEyeOnCcsCalibration(EyeOnCcsCalibration):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mbisdk.NonReducedEyeOnCcsCalibration_swiginit(self, _mbisdk.new_NonReducedEyeOnCcsCalibration(*args))

    def ReductionFactor(self, M_ion, Z):
        return _mbisdk.NonReducedEyeOnCcsCalibration_ReductionFactor(self, M_ion, Z)
    __swig_destroy__ = _mbisdk.delete_NonReducedEyeOnCcsCalibration

# Register NonReducedEyeOnCcsCalibration in _mbisdk:
_mbisdk.NonReducedEyeOnCcsCalibration_swigregister(NonReducedEyeOnCcsCalibration)
class MBIFileHDF5Adapter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ERR_UNEXPECTED = _mbisdk.MBIFileHDF5Adapter_ERR_UNEXPECTED
    ERR_SUCCESS = _mbisdk.MBIFileHDF5Adapter_ERR_SUCCESS
    ERR_HDF5_INTERNAL_ERROR = _mbisdk.MBIFileHDF5Adapter_ERR_HDF5_INTERNAL_ERROR
    NAME_SIZE = _mbisdk.MBIFileHDF5Adapter_NAME_SIZE
    HDF5_METADATA_SIZE_UPPER_LIMIT = _mbisdk.MBIFileHDF5Adapter_HDF5_METADATA_SIZE_UPPER_LIMIT

    def __init__(self, path, accessMode, parent):
        _mbisdk.MBIFileHDF5Adapter_swiginit(self, _mbisdk.new_MBIFileHDF5Adapter(path, accessMode, parent))
    __swig_destroy__ = _mbisdk.delete_MBIFileHDF5Adapter

    def Init(self):
        return _mbisdk.MBIFileHDF5Adapter_Init(self)

    def Close(self):
        return _mbisdk.MBIFileHDF5Adapter_Close(self)

    def GetFilename(self):
        return _mbisdk.MBIFileHDF5Adapter_GetFilename(self)

    def GetFrameStartTime(self, pFrameMD):
        return _mbisdk.MBIFileHDF5Adapter_GetFrameStartTime(self, pFrameMD)

    def GetCalibration(self, pFrameMD):
        return _mbisdk.MBIFileHDF5Adapter_GetCalibration(self, pFrameMD)

    def HasScanDefinitions(self):
        return _mbisdk.MBIFileHDF5Adapter_HasScanDefinitions(self)

    def loadSparseSampleIntensities(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_loadSparseSampleIntensities(self, frameIndex)

    def loadScanSampleIndexPairs(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_loadScanSampleIndexPairs(self, frameIndex)

    def loadScanSampleOffsets(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_loadScanSampleOffsets(self, frameIndex)

    def loadScanIndexPairOffsets(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_loadScanIndexPairOffsets(self, frameIndex)

    def LoadTriggerTimeStamps(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_LoadTriggerTimeStamps(self, frameIndex)

    def loadFrameMetadata(self, frameIndex, metadataMap):
        return _mbisdk.MBIFileHDF5Adapter_loadFrameMetadata(self, frameIndex, metadataMap)

    def LoadScanDefinition(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_LoadScanDefinition(self, frameIndex)

    def LoadScanDefinitionSP(self, frameIndex):
        return _mbisdk.MBIFileHDF5Adapter_LoadScanDefinitionSP(self, frameIndex)

    def NumScanDefinitions(self):
        return _mbisdk.MBIFileHDF5Adapter_NumScanDefinitions(self)

    def LoadRtTic(self, rtTic):
        return _mbisdk.MBIFileHDF5Adapter_LoadRtTic(self, rtTic)

    def LoadAtTic(self, nFrameIndex, nSize):
        return _mbisdk.MBIFileHDF5Adapter_LoadAtTic(self, nFrameIndex, nSize)

    def LoadGlobalMetadataToMap(self, mapMetaAll):
        return _mbisdk.MBIFileHDF5Adapter_LoadGlobalMetadataToMap(self, mapMetaAll)

    def LoadFrameMetadataToMap(self, frameIndex, mapMetaAll):
        return _mbisdk.MBIFileHDF5Adapter_LoadFrameMetadataToMap(self, frameIndex, mapMetaAll)

    def GetErrorCode(self):
        return _mbisdk.MBIFileHDF5Adapter_GetErrorCode(self)

    def GetErrorMessage(self):
        return _mbisdk.MBIFileHDF5Adapter_GetErrorMessage(self)

# Register MBIFileHDF5Adapter in _mbisdk:
_mbisdk.MBIFileHDF5Adapter_swigregister(MBIFileHDF5Adapter)

